### ISSUE TITLE
Feature Request: clean dust bin // Staubbehälter reinigen Notification

### ISSUE THREAD

**Issue by AshleyMiller9696** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#111]
Notification or Sensor to Clean the dust bin like in the App

Benachrichtigung bzw Sensor zum entleeren des Staubbehälters aus der App in Homekit integrieren

**Comment by nicoh88** [comment]
Sounds good, I would also like to.
I think it is not possible because the miio api does not transmit this data.

@afharo 
An occupancy sensor, if "dustbin = true" in config.json, detected if ... no data over miio, no care sensor for dust bin... 👎 

Do you have any idea? Have you ever noticed anything?

**Comment by afharo** [comment]
I need to test it but I think it’s emitted as an error from the miio library. At the moment, we only log it as a warning.
We could set a lock based on that. And the user will need to unlock it manually when it’s fixed (because there’s no way to know it’s clean now).
Maybe even reuse the same lock to rename it based on any warning we emit? 🤔

**Comment by afharo** [comment]
Bumping this issue. I think that, after the latest refactor, it may be pretty easy to implement.

cc @luc-ass as he recently requested something like that

**Comment by afharo** [comment]
It should be solved in https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.26.0
