### ISSUE TITLE
Semi automatic rooms

### ISSUE THREAD

**Issue by funkyremi** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#177]
Hi,
I don't know how to complete that part of the semi automatic configuration:
`Then in the app, setup a timer at midnight (00:00 or 12:00am). Enable Select a room to divide. Then on the map select the rooms in the order as they appear in the homebridge config.`
When I click on timer in the Roborock App, I don't have the ability to select a room to divide.

**Comment by afharo** [comment]
Hi, I don't know how the Roborock app works. Especially since there is an ongoing issue where folks are trying to figure out how to extract the token from it (https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/104).

In the Xiaomi Home app, open your robot settings and `Timer` shows up as the second entry in the list.

**Comment by funkyremi** [comment]
Ok thanks
