### ISSUE TITLE
Filter sensors&Switch

### ISSUE THREAD

**Issue by netRunner0** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#201]
Please add filter (occupancy) sensors and filter reset switch 😉

**Comment by bedrin** [comment]
Related to https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/111

**Comment by afharo** [comment]
Also related to #145 

The sensors are already in place. But HomeKit simply hides the filters statuses and it understands Fans (the type of device we use to report this device) do not require filters.
They can be handled in the Eve app.

Additionally, I understand many of the features requested for automation purposes and, maybe, some useful Siri commands. However, sometimes I feel like we are simply trying to replicate all the features in the Xiaomi app to the Home app just for the sake of it... 🤔 

Maybe it's me, that I'm missing the point and need further understanding of the use case. But these robots' APIs are highly undocumented. They require lots of testing and hacking around and the spare time I personally can pay to this module is fairly limited.

I try to quickly jump on fixing bugs and answering to Pull Requests and Issues. I don't want to be a blocker for anyone's ideas nor keep them waiting. But the more features we provide, the more likely we'll have bugs or opened issues to support them for other models or simply asking how these features work. That adds a lot of overhead to keeping a clean list of issues.

I, personally, use the `homebridge-automation-switches` plugin to automate any switches/sensors I may need based on other plugins values (i.e.: I only want the robot to clean once a day when I leave, so I set a switch when it starts cleaning and reset it every morning. Then check the state of that switch whenever I leave to trigger the full house cleaning or not).

That said, I'll leave this request open should anyone else wants to implement it.

**Comment by netRunner0** [comment]
@afharo You can use the global variables plugin, and not clog HomeKit with unnecessary devices:

Global Variable for HomeKit

I want to present you an easy plug-in for Homebridge, which will allow you to store and exchange data in JSON format between automation and other systems:

[Install](https://www.npmjs.com/package/homebridge-netrunner-http-db)

sudo npm i -g homebridge-netrunner-http-db --unsafe-perm


This plugin will allow you to write complex logic for your automation, exchange data between automation, enable or disable other automation, as well as use the recorded data in other systems.

To add a new variable or overwrite an existing one, use a POST request from the Shortcuts component set - http://ip:15015/variablename

Data can also be sent as an attached file in dictionary format.

To update or add a key in a variable, use a request of type PUT

To get a variable, use a query like GET

Data is stored in JSON format (dictionary). The number of keys in a variable is unlimited.

To get a list of variables, use a GET request without specifying a variable name - http://ip:15015/

I also wrote a convenient editor for already created variables (please use it only for existing variables).
Be sure to change the URL to yours at the beginning of the command!

Have a good use!

**Comment by netRunner0** [comment]
As for filters, but now there is an opportunity to see the status, but there is no way to check it every time I start, for example, to notify me via telegram or push

**Comment by afharo** [comment]
Thank you for the plugin suggestion. I'll check it out.

Re the filters, the Xiaomi app already notifies you out of the box when any of the filter, brushes, sensors and even the dust bin needs any attention. That's why I can't see the need to add more switches and services to this plugin (that we have to maintain and also increases the number of switches in the Home app).

But, if you still want to react to any of those values, you can set any triggers and automation via the Eve app (no need for the Shortcuts app at this point). Also, please, check the version `0.10.0` which adds a unified Filter status, merging all filter + main and side brush + sensors statuses into one as explained in #203

Nevertheless, feel free to create a pull request adding that feature and I'll be happy to merge it.

**Comment by bedrin** [comment]
Plugins mentioned here could go to https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/202 as well!

**Comment by mitch7391** [comment]
@afharo I understand how you would not want to add the filter, brushes and sensors as extra accessories, but is there a chance to have them 'alarm' as statuses on the accessories? For example how a temperature sensor has the status for a battery level (sorry if I am not using the right terminology) and it will put an alert or alarm condition on the accessory to say something is wrong with it. Can we not do that for these? Personally I turn off all notifications from the Xiaomi app as I do not want it to tell me every time it starts or finishing vacuuming, the only notifications I want are these ones for the maintenance. I find now I am always behind on maintaining my robot as I turned off the notifications...

**Comment by afharo** [comment]
They already exist registered as `Filters`. 

HomeKit doesn't allow you to add more than 1 filter per accessory. 

So there's a general one, showing the worse value assigned to the fan accessory:
<img width="306" alt="image" src="https://user-images.githubusercontent.com/5469006/95328320-5098a200-089d-11eb-858f-d45d0a90a93b.png">

And one individual one for each indicator.

The problems are:

1. HomeKit doesn't expect filters to be attached to **fan** accessories (that's why you may have noticed a few [`HAP Warning... Adding Anyway`](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/257) entries in the logs). So it doesn't allow you to build any automation via the Home/Shortcuts app.
2. The Home app doesn't show the additional Filter accessories.

You can use the [Eve app](https://www.evehome.com/en/eve-app) to access those _non-official_ indicators. You can set automations in that app and they'll work in the Home app. Personally, when I started in this, I was surprised how powerful the Homekit automations can be, but also how limited the Home app's UI is to set them. The Eve app is the solution for these issues 😉 

More info: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/145

**Comment by afharo** [comment]
Also, known missing piece re the Filters: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/211

**Comment by mitch7391** [comment]
@afharo thanks for the info. I have avoided Eve for a long time as I have tried to keep all of the apps all my devices use to a minimum and would prefer Homekit to be the one place everything is controlled (at the cost of better automations by the looks haha). Maybe this screenshot better describes what I mean (except in the is particular case they have an issue where the battery fault appears whilst the battery level is not low; ignore that aspect). This shows that a warning `!` or a status 'Battery Low' can be displayed based for these characteristics (filter, battery, etc) on the accessory; that is what I am asking if it is possible so that the accessory shows me that something needs attention. 

![image](https://user-images.githubusercontent.com/40288237/95335088-88293d80-08e1-11eb-9a67-b419195ba037.png)

I only have a quick skim read for now, but it looks like that is being touched on by netRunner0 in issue 145, where they point out these characteristics. But I am not sure if these ones have something like 'Status Fault' or not.

**Comment by afharo** [comment]
@mitch7391 I understand what you are saying. 

But the reason it is shown in the screenshot you shared is that HomeKit officially supports the battery status in `TemperatureSensor`s: in [this piece of code](https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/gen/HomeKit.ts#L5053-L5076), maintained in the library `HAP-NodeJS` by generating it from the Homekit specifications, you can see `TemperatureSensor` has the optional characteristic `StatusLowBattery`.

The [`Fan` service](https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/gen/HomeKit.ts#L4414-L4435) though doesn't _accept_ it. We report it anyway and (luckily) it is shown in the Home app. However, the Home app doesn't show it for notifications or automation rules.

You can use the Eve app to build any automation rules you may want and then uninstall it. You don't need it installed in order for them to work. You only need it because it has a more flexible UI to build automation rules and to see all the characteristics, both: officially supported and non-officially ones.

**Comment by mitch7391** [comment]
Ahh yep that makes more sense and a shame the fan service doesn’t cater for this; hopefully Apple will just give us a real robot vacuum accessory soon! Also I didn’t know you could do that with Eve, I’m going to have a look into it :)

**Comment by afharo** [comment]
> hopefully Apple will just give us a real robot vacuum accessory soon!

Can't wait for that to happen!

**Comment by luc-ass** [comment]
Anyone still working on this? Now that the go-to-button works, I desperately want to know wether the dust bin is actually full... Right now I am sending my vacuum to the kitchen when I come home on Wednesdays 😜

@afharo I'd like to contribute, but my knowledge around TS is practically zero...

**Comment by afharo** [comment]
@luc-ass FWIW, all the maintenance indicators are reported to Homekit. And they show up in applications that are more _pro_ than Apple's Home app. The reason is that Homekit doesn't consider a **Fan** should have any of those Filter indicators (which sort of makes sense), so the Home app simply ignores them.

My app of choice for low-level automations is [Controller for Homekit](https://apps.apple.com/es/app/controller-for-homekit/id1198176727?l=en). I used to like the Eve app, but they changed it and started hiding many non-officially-supported attributes (Services & Characteristics), and it lost most of the low-level access.

Here are some screenshots of the existing maintenance indicators showing up in that app:

**Overall status:**

Shows the worst state of the maintenance indicators (if any of them needs attention, this will show `Needed` and `0%`):
![image](https://user-images.githubusercontent.com/5469006/187633426-b65ca1e0-8bb9-493a-843f-fc1fb08ab218.png)

This one shows up in the Home app, but it doesn't allow you to use it in automations because _Apple being Apple_:
![image](https://user-images.githubusercontent.com/5469006/187634046-5cbd629a-a8fe-4d9f-b2e2-4dde8cb1ca38.png)

**Individual maintenance indicators:**
![IMG_2104](https://user-images.githubusercontent.com/5469006/187634461-edff9485-4561-4de7-a13b-4711aea5007e.PNG)
_You may notice the Main brush is 38%, so it should show up in the overall status. This is fixed and will be available in the next version._

Another reason for using 3rd-party tools for detailed automations is **they are more accurate**. For example, look at the Firmware version in the Home app vs. the Controller app. It is a standard and officially supported field, but apparently, Apple Home thinks the Firmware cannot change over time, so it doesn't react to updates in that field 🤦 
![image](https://user-images.githubusercontent.com/5469006/187635511-63499555-9dc0-4c3c-b634-01c2692b4735.png)
![image](https://user-images.githubusercontent.com/5469006/187635567-6ec052a9-2ae9-474e-b3fc-9f709dfd90e9.png)

One thing you may argue is that we don't have a switch to reset any of these maintenance indicators. PRs are welcomed if you think they'd be useful: my take on this one is that you should need to replace the brush once a year, so I'd rather have the reset button as an advanced setting in the Xiaomi app than a switch in Home that anyone (including my 2 y/o kid) can hit and reset without notifying anyone.

--------------------

@luc-ass re your use case, I believe you are looking at the dust bin status, correct? I'm not sure there is a level for that, but instead, we'd need to react to an error code. IMO, we could react to the relevant code error and trigger an occupancy sensor to indicate it needs the dust bin to be emptied. You could then set an automation that reacts to that occupancy sensor and send the robot to your kitchen. 

That'd be a dream unless it happens halfway through a cleaning session because it'd cancel the cleaning to go to your kitchen (and potentially run out of battery while waiting for you there until you come back home). If it's only used for notification purposes on your phone, I'd say the Xiaomi app already notifies about any errors, so it feels like overdoing at this stage. 

What do you think?

**Comment by luc-ass** [comment]
You are right about the problem of canceling the cleaning process. My automation would be along the lines of:
```
Trigger:   First person comes home / me coming home
Condition: If Dust bin full (could be a switch, could be a sensor)
Execution: Turn "Go to the bin" on
```
An occupancy sensor would need to be reset somehow, no idea on how to implement that. A simple switch could be turned off by hand or some automation. It wouldn't interfere with anything else.
Man, it's really time Apple/Matter implement a Vacuum type 😆

**Comment by luc-ass** [comment]
BTW: For now I made an "Apple Shortcut" that executes when I come home and sends the vacuum to the kitchen when I arrive at home on Wednesdays. Not pretty but works:

![IMG_6E8D8A89E58D-1](https://user-images.githubusercontent.com/3263257/187739928-b282f981-cc71-4747-bb28-97429289ca64.jpeg)

By choosing a custom Date format as `EEEE` you can compare it to the full day name.

**Comment by afharo** [comment]
It should be solved in https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.26.0
