### ISSUE TITLE
HAP Warning... Adding Anyway

### ISSUE THREAD

**Issue by mitch7391** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#257]
When I restart Homebridge, I get the following message each time:

[7/20/2020, 18:09:22] [Roborock] Initializing XiaomiRoborockVacuum accessory...
HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.

I was wondering if there is something I need to change in my config to stop this or if it something in the plug-in throwing this message up?

**Comment by afharo** [comment]
Those correspond to `FilterChangeIndication` and `FilterLifeLevel`. They are used to show the condition of the filters:
![image](https://user-images.githubusercontent.com/5469006/87930605-4a560f00-ca80-11ea-8b71-3a72020efd2c.png)

The reason why it logs with that warning, it's because those two indicators are not "officially" supported by Apple (but you can see from the screenshot they work without issues).

Related to #145

**Comment by mitch7391** [comment]
Ahh that makes sense :) thanks for the explanation, I will just ignore the warning then!
