### ISSUE TITLE
ERR getState | {"code":-10002}

### ISSUE THREAD

**Issue by KIBkz** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#274]
ERR getState | {"code":-10002}

**Comment by afharo** [comment]
Hey! I've been looking around about that code `{"code":-10002}`, and it looks like it means `access denied`. Everywhere I could find references to it, they claimed it's because it's a Chinese model not allowed to work in Europe (or vice-versa). They mention there's the possibility to flash it with a firmware that doesn't apply the regional block (https://forum.xda-developers.com/android/apps-games/app-xvacuum-firmware-xiaomi-vacuum-t3896526/page3)
Does it make sense?

**Comment by KIBkz** [comment]
> Hey! I've been looking around about that code `{"code":-10002}`, and it looks like it means `access denied`. Everywhere I could find references to it, they claimed it's because it's a Chinese model not allowed to work in Europe (or vice-versa). They mention there's the possibility to flash it with a firmware that doesn't apply the regional block (https://forum.xda-developers.com/android/apps-games/app-xvacuum-firmware-xiaomi-vacuum-t3896526/page3)
> Does it make sense?

I'll try that and answer later. Thx

**Comment by ileodo** [comment]
Can we get the around this region block somehow in home bridge? AFAIK, using Xiaomi Mi Home App on a phone which has Chinese SIM card and having UTC+8 can bypass the region block.

Can we somehow simulate this behaviour via home bridge?

**Comment by afharo** [comment]
Maybe changing the TZ of the host where `homebridge` is running? 🤔

**Comment by ileodo** [comment]
but how does the device know the TZ of the `homebridge` host? I guess there is a way to hijack the `miio` communication? not very familiar on the `miio` level, any idea?

**Comment by afharo** [comment]
If you run `homebridge` with the environment variable `DEBUG=*` you'll see all the underlying messages in the `miio` protocol.

**Comment by afharo** [comment]
I'll go ahead and close this issue for now. Please, feel free to reopen it if you think it's worth investing more time in it (and can provide the requested debug logs)
