### ISSUE TITLE
Handshake-timeout

### ISSUE THREAD

**Issue by serverpaul** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#297]
I get a timeout... Im using a Roborock S5 and get this error...
I got it yesterday too i think but then it dissappeared - I can't remember what I did but it's not permanent. 

<img width="899" alt="Bildschirmfoto 2020-10-21 um 17 18 36" src="https://user-images.githubusercontent.com/73078650/96740846-853e4a80-13c1-11eb-9546-2c3b3f159131.png">

**Comment by afharo** [comment]
Hi @serverpaul,
Sometimes, due to network glitches, the plugin fails to connect to the robot. When this happens, it'll retry to connect 2 minutes later until successfully connected.

Sometimes it happens because the vacuum goes under a table or furniture and loses the WiFi connection. If the connection goes back to normal automatically, it seems like the retry mechanism is serving its purpose. I'll go ahead and close the issue. Feel free to reopen it if needed.
