### ISSUE TITLE
Change icon in Home (fan to robot) and change slider to switch

### ISSUE THREAD

**Issue by mrcsdwdn** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#305]
Hi there, first of all thanks for the good work! it works like a charm and i'm really happy to use my roborock s5 max via apple home. Setting all up was quite uncomplicated and i'm happy with the result. Just one question was popping up in my head: is it possible to change the fan icon to a vacuum robot and change from slider to switch? If so, how do I set this up? I'm really looking forward for your answer. Thanks and all the best!

**Comment by afharo** [comment]
Hi @mrcsdwdn 

Thank you for all the good and nice words about your experience with this plugin. It is really appreciated.

At the moment, Apple's Homekit does not support Vaccum robots yet so, unfortunately, we need to find an accessory that behaves in a similar way. That's why we went for a Fan service. The slider allows us to select the speeds. I'm all fingers crossed for Apple to bring in official support for those accessories and I'll update this plugin to report as such.

I hope this answers your question 🙂

**Comment by mrcsdwdn** [comment]
Hi @afharo 
thank you for your answer! Guess we have to wait and hope for the best ;)
Keep up the good work!

**Comment by afharo** [comment]
Yeah! Until then, I'll close this issue if that's OK :)

Thank you again!
