### ISSUE TITLE
Suppress the excessive information log

### ISSUE THREAD

**Issue by uswong** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#473]
Hi,

First of all I would like to thank the author and contributors to this amazing plugin.

As it is at the moment ,I am getting a full screen of information log every 30 seconds or so. Is there a way to suppress it?

![image](https://user-images.githubusercontent.com/96530237/148770180-ebfee37a-36fa-4665-aa89-6ba00cc094a9.png)

Regards,
uswong

**Comment by mitch7391** [comment]
@uswong I swear I am not stalking you, but pretty sure this is due to one I brought up a long time ago and can be solved by adding the following to you config (can be found on the README):

<img width="635" alt="image" src="https://user-images.githubusercontent.com/40288237/149461102-3c78b47a-e7a1-4942-b600-ceffa01f6e7e.png">

You want to set that to `true`.

**Comment by uswong** [comment]
Lol.....Mitch, certainly feel like someone is stalking me....

Thanks for that simple solution!  Haha...it is obvious that I did not read the README properly!    Sorted now and finally I have some space on my homebridge screen to look at messages from other plugins!

**Comment by mitch7391** [comment]
It drives me nuts when my logs are spammed with information I do not need!

**Comment by afharo** [comment]
Thanks @mitch7391 for answering this question.

@uswong do you think that we can close this issue?
