### ISSUE TITLE
There's a problem with setting the speed of the pen.

### ISSUE THREAD

**Issue by yes2310** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#479]
I'm using the s5 max model.

All I seem to function normally speed capability to set the pen isn't seem normal.

I want to use the max mode, but even if I set it to 100%, the max mode does not work.

I have to set it to 67 percent to operate in max mode.

Is there any way to solve this problem or to use the basic output in max mode?

**Comment by afharo** [comment]
The reason is that S5 Max model supports the custom speed. 

Since we only have a dial, 100% is the custom, the previous step, 67%, is Max power.

Here's the code defining those steps:
https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/d0ffdd2161cdbe3947e26d01ab75a9700d187e0e/models/speedmodes.js#L182-L219

**Comment by afharo** [comment]
It looks like the question is resolved. I'll go ahead and close this issue. Feel free to reopen if there are any follow up questions.
