### ISSUE TITLE
Number of times you clean per day

### ISSUE THREAD

**Issue by sercontri** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#482]
Good, I wanted to know if it would be possible to put a cycle counter on it to know if in the course of a day it has already cleaned the house or not. This would be to automate that when the last person leaves the house, they start cleaning unless they have already cleaned that day.

**Comment by martindinicolino** [comment]
good idea, whilst your suggestion would be the more elegant solution this is currently possible (for example by using a dummy switch in homebridge and a couple of HomeKit automations)

**Comment by afharo** [comment]
I agree with @martindinicolino, I currently use `homebridge-automation-switches` for that: I flip a switch (it's actually a `lock`) whenever the cleaner starts. 

IMO, having a dummy switch has some benefits:

1. You control when it should kick in (is it a full clean, a room clean, ...).
2. You control when it should be reset: I do it at 7am. I don't want my robot to kick in if I left the house in the middle of the night for an emergency.
3. It allows you to choose the type of switch that works best for you: I personally use a `lock` because it notifies you when it switches (I have notifications for this switch disabled when I'm at home), so I know that it got successfully triggered.

**Comment by martindinicolino** [comment]
> 3\. I personally use a `lock` because it notifies you when it switches (I have notifications for this switch disabled when I'm at home), so I know that it got successfully triggered.

Thank you for your insights, that sounds like an interesting expansion on what I've got currently going on, I installed the plugin you mentioned, but I still haven't figured out how to set up config-based homebridge plugins (maybe someday I'll get there, so thank you for the tip @afharo)

I just use `Homebridge Dummy` and the setup couldn't be easier - 10/10, I would totally recommend it to newbies like myself

**Comment by afharo** [comment]
I'll go ahead and close this issue. However, I think these notes would be great in #202 for others to find it when they are setting up their plugins.
