### ISSUE TITLE
Device Tile presented as Switch Instead of Fan 

### ISSUE THREAD

**Issue by vskal** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#542]
Thx for the great plugin !

Since the recent Go To functionality update, the Roborock grouped tile is presented as a switch instead of a fan (which greatly helps to visualy differentiate it).

Is there a way to have them presented as a fan ?

**Comment by Lammiwinks** [comment]
Im experiencing the same issue!

**Comment by Lammiwinks** [comment]
Can confirm - service type is set to Fan. But it appears the tile is showing the status of presence on the dock rather than the fan. 

i.e. the accessories are grouped with the presence set as the main item.
![IMG_6576](https://user-images.githubusercontent.com/101758754/188562798-1ce805ba-7da3-4aa6-83ec-053d609b892f.jpeg)
![IMG_6577](https://user-images.githubusercontent.com/101758754/188562815-109dcd6e-a332-40c3-a777-679950d1b9e0.jpeg)

**Comment by luc-ass** [comment]
Really strange behaviour. Mine displays as as switch as well. For now the only fix I found was to show it as separate accessories -- though that might not be wat you want...

**Comment by Lammiwinks** [comment]
How did you show as seperate accessories?

**Comment by afharo** [comment]
Can you confirm [v0.27.0](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.27.0) fixed these issues, please?

**Comment by luc-ass** [comment]
Seems to work for me (though it has been a fan since I needed to reinstall the plugin). Curious if this fixes the issue for other people.
