### ISSUE TITLE
Potential issue with iOS 16

### ISSUE THREAD

**Issue by maisun** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#552]
Hi, after upgrading to iOS 16 in the device group looks like all switches now inherit the name of the main accessory. Is it an issue with iOS or homebridge? Anybody else experience the same issue?

**Comment by afharo** [comment]
It looks like a common issue. I have other plugins showing the same issue: all related accessories share the same name.

Although I'm not sure if it's iOS16 or homebridge. I'd say it's iOS16 changing the way it behaves... but since I doubt Apple will fix it, it will likely be homebridge the one to fix it...

Nothing we can do from the plugin POV, AFAIK.

**Comment by afharo** [comment]
It looks like this is the issue tracking that bug in the `homebridge` repository: https://github.com/homebridge/homebridge/issues/3210

They mention it's an iOS16 bug and looks like they are not planning to fix it.

However, there is a workaround: clearing the name in the Home App shows the placeholder of the original name
