### ISSUE TITLE
New Room name push kills my switches

### ISSUE THREAD

**Issue by MirkoKas** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#841]
The included new push of the room names at the start of the plugin, renames all my switches in HomeKit. 
I have to rename them manually, because in the German language you put the verb at the end. 
e.g. Wohnzimmer reinigen, Küche reinigen,…

Two suggestions for a fix:

a) Option to set wether the cleaning word should be before or after the room name
b) make the room name push optional within the settings of the plugin

**Comment by afharo** [comment]
Oh! I'm sorry to learn that it broke it for you.

Can you confirm if this issue occurs every time Homebridge is restarted? Or did it happen only once?

**Comment by afharo** [comment]
I'll take a look! I'll see if we can check if the names have been changed by the user. If so, we'll skip without any required additional config 😇

**Comment by afharo** [comment]
It should be fixed in the latest release: [0.31.1](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.31.1)

Bear in mind that it will require that you set your custom names one last time. After that, the plugin will persist your preference and won't overwrite it any more.

**Comment by MirkoKas** [comment]
Just did a quick test and it seems to work. Names stay the same even after a restart of the child bridge. 

Thank you for your quick fix.
